### ISSUE TITLE
Version numbers for bootstrap scripts

### ISSUE THREAD

**Issue by SamFrier** [UKHomeOffice/development_environment#93]
## Expected Behavior

The development environment should include a version number (both for the PXE and Ansible steps) that is updated after every noteworthy change.

## Current Behavior

The repository has used tags in the past but these haven't been updated in several months.

## Possible Solution

Possibly include version number in a file or as an ansible fact?

## Steps to Reproduce (for bugs)

N/A

## Context

Request courtesy of @Ian-T-Price -- currently there are multiple versions of the build scripts floating around among DevOps and they would like to be able to distinguish which version they are / should be on.

## Your Environment

N/A

**Comment by pixie79** [comment]
This is expected behaviour - we are not supposed to be deploying development branches only the master branch which gets tagged once it has been pen tested (ITHC). We have not had a fresh ITHC recently hence why there have been no tags. When everyone it happy the repo is building correctly then we can request a ITHC and create a tag.
